#!/bin/bash

echo "🚀 推送代码到 GitHub"
echo "======================================"
echo ""
echo "你的 GitHub 用户名: wengodgarden-max"
echo "你的仓库链接: https://github.com/wengodgarden-max/-.git"
echo ""
echo "======================================"
echo ""
echo "在项目目录执行以下命令："
echo ""
echo "cd /workspace/projects"
echo "git remote add origin https://github.com/wengodgarden-max/-.git"
echo "git push -u origin main"
echo ""
echo "======================================"
echo ""
echo "如果需要认证，GitHub 会要求你输入："
echo "1. GitHub 用户名"
echo "2. GitHub 密码（需要使用 Personal Access Token）"
echo ""
echo "如何创建 Token："
echo "1. 打开 https://github.com/settings/tokens"
echo "2. 点击 'Generate new token (classic)'"
echo "3. 勾选 'repo' 权限"
echo "4. 生成并复制 token"
echo "5. 在推送时，密码处粘贴 token"
