#!/bin/bash

echo "🚀 炼金师助手 - 快速部署指南"
echo "================================"
echo ""
echo "📋 准备工作："
echo "1. 确保你有一个 GitHub 账号"
echo "2. 确保你已在本地测试过（python src/main.py）"
echo ""
echo "📦 步骤1: 推送代码到 GitHub"
echo "----------------------------------------"
echo "git init"
echo "git add ."
echo "git commit -m 'feat: 炼金师助手初始化'"
echo "git branch -M main"
echo "git remote add origin https://github.com/你的用户名/你的仓库名.git"
echo "git push -u origin main"
echo ""
echo "🌐 步骤2: 部署到 Railway（推荐）"
echo "----------------------------------------"
echo "1. 访问 https://railway.app"
echo "2. 点击 'Login with GitHub'"
echo "3. 点击 'New Project'"
echo "4. 选择 'Deploy from GitHub repo'"
echo "5. 选择你的仓库"
echo "6. 等待部署完成（约2-3分钟）"
echo ""
echo "✅ 步骤3: 获得公开链接"
echo "----------------------------------------"
echo "部署完成后，Railway 会给你一个永久链接："
echo "https://你的项目名-production-xxxx.up.railway.app"
echo ""
echo "访问地址："
echo "- 主页：https://你的链接/"
echo "- 炼金师：https://你的链接/alchemist"
echo ""
echo "🎉 完成！现在可以在小红书推广了！"
echo ""
echo "💡 小红书话术："
echo "----------------------------------------"
echo "🎁 免费体验链接：https://你的链接/alchemist"
echo "新用户免费体验5轮对话"
echo "满意再付费解锁完整产出！"
echo "💰 套餐：体验版¥9.9 | 标准版¥29.9 | 年度会员¥99"
echo "私信获取激活码～"
